thingspeak/config/routes.rb
Thingspeak::Application.routes.draw do

  #pist routes
  #get '/appli/login', to: 'login#login'
  get '/appli', to: 'appli#index'
  get '/appli/channels', to: 'appli#channels'
  get '/appli/channels/newchannel', to: 'appli#newchannel'
  get 'appli/configuration/get-keys', to: 'appli#getkeys'
  get 'appli/configuration/refresh', to: 'appli#refresh'
  get 'appli/configuration/unbind-key', to: 'appli#unbind_key'
  get 'appli/key_registrations', to: 'appli#key_registrations'
  get 'appli/getCapteurTemp', to: 'appli#getCapteurTemp'
  get 'appli/getAPIKeys', to: 'appli#getAPIKeys'
  get 'appli/sensors', to: 'appli#sensors'

  # admin routes
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  # main data posts using this route
  match 'update', :to => 'channels#post_data', :via => ((GET_SUPPORT) ? [:get, :post] : :post)
  match 's/update', :to => 'channels#post_data', :via => [:get, :post]

  # handle subdomain routes
  get '/', :to => 'subdomains#index', :constraints => { :subdomain => 'api' }
  get 'crossdomain', :to => 'subdomains#crossdomain', :constraints => { :subdomain => 'api' }

  root :to => 'pages#home'

  # for api: login and get token
  match 'users/api_login', :to => 'users#api_login', :via => [:get, :post]

  # devise for authentication
  # override devise controllers and use custom sessions_controller and registrations_controller
  devise_for :users, :controllers => {:sessions => 'sessions', :registrations => 'registrations'}

  resource :pages do
    collection do
      get :home
      get :about
      get :headers
      get :social_home
      post :contact_us
    end
  end

  match 'users/reset_password/:id', :to => 'users#reset_password', :as => 'reset_password', :via => [:get, :post]
  patch 'users/change_password/:id', :to => 'users#change_password'
  post 'mailer/resetpassword', :to => 'mailer#resetpassword'

  # public user profiles
  match 'account/edit_profile' => 'users#edit_profile', :as => 'edit_profile', :via => [:get, :post]
  patch 'account/update_profile' => 'users#update_profile', :as => 'update_profile'
  # users paths
  post 'users/new_api_key' => 'users#new_api_key', :as => 'user_new_api_key'
  get 'users/:id/channels(.:format)' => 'users#list_channels', :as => 'list_channels', :constraints => { :id => /.*/ }
  get 'users/:glob' => 'users#profile', :as => 'user_profile', :constraints => { :glob => /.*/ }

  resource :user_session
  resource 'account', :to => 'users'
  resources :users

  # social channels
  get 's/' => 'pages#social_home'
  get 's/:slug' => 'channels#social_show', :constraints => { :slug => /.*/ }
  get 'channels/social_new' => 'channels#social_new'

  # search
  resources :tags

  # maps
  get 'channels/:channel_id/maps/channel_show' => 'maps#channel_show'
  get 'channels/:channel_id/status/recent' => 'status#recent'

  # multiple series on a chart demo
  get 'charts/multiple_series' => 'charts#multiple_series'

  # nest the following controllers inside channels
  resources :channels do
    collection do
      get :public
      get :watched
      get :realtime
    end
    member do
      get :import
      post :upload
      post :clear
      put :watch
      post :realtime_update
    end
    resources :feed

    resources :feeds, :to => 'feed'
    resources :api_keys, :except => [:show, :edit]
    resources :status
    resources :statuses, :to => 'status'
    resources :charts
    resources :maps
    resources :channels
    resources :tags
    resources :comments
    resources :windows, :only => [:index, :update] do
      member do
        get :iframe
        get :html
        put :hide
        put :display
      end
    end
  end

  get 'channels/:channel_id/private_windows' => 'windows#private_windows'
  get 'channels/:channel_id/hidden_windows' => 'windows#hidden_windows'
  match 'channels/:channel_id/windows' => 'windows#update', :via => [:post, :put]

  resources :comments do
    member do
      post :vote
    end
  end

  resources :plugins do
    collection do
      get 'private_plugins'
      get 'public_plugins'
      #get 'public'
    end
  end

  resources :devices do
    member do
      get :thingtweet_arduino_code
      get :thingtweet_arduino_select_thingtweet
      post :add_mac_address
      put :ajax_update
    end
  end

  resources :pipes

  # twitter status update (version 1)
  match 'apps/thingtweet/1/statuses/update(.:format)' => 'thingtweets#update', :via => [:get, :post]
  match 'apps/thingtweet/1/statuses/update_debug(.:format)' => 'thingtweets#update_debug', :via => [:get, :post]


  # thinghttp action
  match 'apps/thinghttp/send_request' => 'thinghttp#send_request', :via => [:get, :post]

  # process responses for tweetcontrol
  match 'apps/tweetcontrol/process_response' => 'tweetcontrol#process_response', :via => [:get, :post]

  # apps and nested controllers
  scope 'apps' do
    resources :thingtweets do
      collection do
        get :authorize_response
      end
      member do
        put :new_api_key
      end
    end
    resources :thinghttp do
      resources :header
      member do
        put :new_api_key
      end
    end
    resources :talkbacks do
      member do
        put :new_api_key
      end
    end
    resources :tweetcontrol
    resources :reacts
    resources :timecontrols
  end

  # talkback api
  delete 'talkbacks/:talkback_id/commands', :to => 'commands#destroy_all'
  delete 'talkbacks/:talkback_id/commands/destroy_all', :to => 'commands#destroy_all'
  resources :talkbacks do
    resources :commands do
      collection do
        match :execute, :via => [:post, :get]
        delete :destroy_all
      end
    end
  end

  resources :apps, :only => ['index']

  # admin signups by day
  get 'admin/signups', :as => 'admin_signups', :to => 'admin/users#signups'
  # admin list of all email addresses
  get 'admin/emails', :as => 'admin_emails', :to => 'admin/users#emails'

  # app shortcuts
  get 'apps/thingtweet', :to => 'thingtweets#index'
  get 'apps/react', :to => 'react#index'


  # users
  devise_scope :user do
    match 'login', to: "devise/sessions#new", :via => [:get, :post]
    match 'logout', to: "devise/sessions#destroy", :via => [:get, :post]
  end

  # streaming routes
  match '/stream/channels/:id/feeds(.:format)', to: 'stream#channel_feed', :via => [:get, :post]

  # add support for CORS preflighting (matches any OPTIONS route up to 5 levels deep)
  # examples: /talkbacks, /talkbacks/4, /talkbacks/4/commands, /talkbacks/4/commands/6, /apps/thingtweet/1/statuses/update
  match '/:foo(/:foo(/:foo(/:foo(/:foo))))', :to => 'cors#preflight', :via => 'options'

  #match ':controller(/:action(/:id(.:format)))', :via => :all
end

thingspeak/app/models/chart.rb
class Chart
  def self.default_width
    450
  end
  def self.default_height
    250
  end
end

thingspeak/app/controllers/charts_controller.rb
class ChartsController < ApplicationController
  before_filter :require_user, :only => [:edit]

  def edit
    # params[:id] is the windows ID
    @channel = current_user.channels.find(params[:channel_id])

    window_id = params[:id]
    logger.debug "Windows ID is #{window_id}"
    window = @channel.windows.find(window_id)
    options = window.options unless window.nil?
    logger.debug "Options for window #{window_id} are " + options.inspect

    render :partial => "charts/config", :locals => {
      :displayconfig => false,
      :title => @channel.name,
      :src => "/channels/#{@channel.id}/charts/#{window_id}",
      :options => options,
      :index => window_id,
      :width => Chart.default_width,
      :height => Chart.default_height
    }
  end

  def index
    set_channels_menu
    @channel = Channel.find(params[:channel_id])
    @channel_id = params[:channel_id]
    @domain = domain

    # default chart size
    @width = Chart.default_width
    @height = Chart.default_height

    check_permissions(@channel)
  end

  # show a chart with multiple series
  def multiple_series
    render :layout => false
  end

  def show
    # allow these parameters when creating feed querystring
    feed_params = ['key', 'api_key', 'apikey', 'days','start','end','round','timescale','average','median','sum','results','location','status','timezone','offset','min','max']

    # set chart size
    width = params[:width].present? ? params[:width] : Chart.default_width
    @width_style = (width == 'auto') ? '' : "width: #{width.to_i - 25}px;"
    height = params[:height].present? ? params[:height] : Chart.default_height
    @height_style = (height == 'auto') ? '' : "height: #{height.to_i - 25}px;"

    # add extra parameters to querystring
    @qs = ''
    params.each do |p|
      @qs += "&#{p[0]}=#{p[1]}" if feed_params.include?(p[0])
    end

    # fix chart colors if necessary
    params[:color] = fix_color(params[:color])
    params[:bgcolor] = fix_color(params[:bgcolor])

    # set ssl
    ssl = (get_header_value('x_ssl') == 'true')
    @domain = domain(ssl)

    # should data be pushed off the end in dynamic chart
    @push = (params[:push] and params[:push] == 'false') ? false : true
    @results = params[:results]
    render :layout => false
  end

  # save chart options
  def update
    @channel = Channel.find(params[:channel_id])
    @status = 0

    # check permissions
    if current_user.present? && @channel.user_id == current_user.id
      logger.debug "Saving Data with new options " + params[:newOptions].to_s
      # save data
      if params[:newOptions]
        logger.debug "Updating new style options on window id #{params[:id]} with #{params[:newOptions][:options]}"
        window = @channel.windows.find(params[:id])
        window.options = params[:newOptions][:options]
        if !window.save
          raise "Couldn't save the Chart Window"
        end
      end
      if @channel.save
        @status = 1
      end

    end

    # return response: 1=success, 0=failure
    render :json => @status.to_json
  end

  private

  # fixes chart color if user forgets the leading '#'
  def fix_color(color)
    # check for 3 or 6 character hexadecimal value
    if (color and color.match(/^([0-9]|[a-f]|[A-F]){3}(([0-9]|[a-f]|[A-F]){3})?$/))
      color = '#' + color
    end

    return color
  end

end

thingspeak/app/helpers/charts_helper.rb
module ChartsHelper
end

thingspeak/app/views/charts/_config.html.erb
<div id="chartOptions<%= index %>" class="chartOptions"><%= options %></div>

  <table class="FL MR60">
    <tr>
      <td><%= t(:title) %>:</td>
      <td><input type="text" class="chart_options<%= index %>" id="title_<%= index %>" /></td>
    </tr>
    <tr>
      <td><%= t(:chart_xaxis) %>:</td>
      <td><input type="text" class="chart_options<%= index %>" id="xaxis_<%= index %>" /></td>
    </tr>
    <tr>
      <td><%= t(:chart_yaxis) %>:</td>
      <td><input type="text"  class="chart_options<%= index %>" id="yaxis_<%= index %>" /></td>
    </tr>
    <tr>
      <td><%= t(:chart_color) %>:</td>
      <td><input type="text" class="chart_options<%= index %>" id="color_<%= index %>" /></td>
    </tr>
    <tr>
      <td><%= t(:chart_background_color) %>:</td>
      <td><input type="text" class="chart_options<%= index %>" id="bgcolor_<%= index %>" /></td>
    </tr>
    <tr>
      <td><%= t(:chart_type) %>:</td>
      <td>
  <select class="chart_options<%= index %>" id="type_<%= index %>">
    <option>line</option>
    <option>bar</option>
    <option>column</option>
    <option>spline</option>
  </select>
      </td>
    </tr>
    <tr>
      <td><%= t(:chart_is_dynamic) %>:</td>
      <td>
  <select class="chart_options<%= index %>" id="dynamic_<%= index %>" >
    <option value=""></option>
    <option value="true">True</option>
  </select>
      </td>

    </tr>

    <tr>
      <td><%= t(:days) %>:</td>
      <td><input type="text" class="chart_options<%= index %> shortfield" id="days_<%= index %>" /></td>
    </tr>
    <tr>
      <td><%= t(:results) %>:</td>
      <td><input type="text" class="chart_options<%= index %> shortfield" id="results_<%= index %>" /></td>
    </tr>
<% if displayconfig %>
    <tr>
      <td><%= t(:width) %>:</td>
      <td><input type="text" class="chart_options<%= index %> shortfield" id="width_<%= index %>" /></td>
    </tr>
    <tr>
      <td><%= t(:height) %>:</td>
      <td><input type="text" class="chart_options<%= index %> shortfield" id="height_<%= index %>" /></td>
    </tr>
<% end %>


  </table>

  <table>
    <tr>
      <td><%= t(:timescale) %>:</td>
      <td>
  <select class="chart_options<%= index %> mutuallyexclusive<%= index %>" id="timescale_<%= index %>" >
    <option value=""></option>
    <option value="10">10</option>
    <option value="15">15</option>
    <option value="20">20</option>
    <option value="30">30</option>
    <option value="60">60</option>
    <option value="240">240</option>
    <option value="720">720</option>
    <option value="1440">1440</option>
  </select>
      </td>

    </tr>

    <tr>
      <td><%= t(:average) %>:</td>
      <td>
  <select class="chart_options<%= index %> mutuallyexclusive<%= index %>" id="average_<%= index %>" >
    <option value=""></option>
    <option value="10">10</option>
    <option value="15">15</option>
    <option value="20">20</option>
    <option value="30">30</option>
    <option value="60">60</option>
    <option value="240">240</option>
    <option value="720">720</option>
    <option value="1440">1440</option>
  </select>
      </td>
    </tr>
    <tr>
      <td><%= t(:median) %>:</td>
      <td>
  <select class="chart_options<%= index %> mutuallyexclusive<%= index %>" id="median_<%= index %>" >
    <option value=""></option>
    <option value="10">10</option>
    <option value="15">15</option>
    <option value="20">20</option>
    <option value="30">30</option>
    <option value="60">60</option>
    <option value="240">240</option>
    <option value="720">720</option>
    <option value="1440">1440</option>
  </select>
      </td>
    </tr>
    <tr>
      <td><%= t(:sum) %>:</td>
      <td>
  <select class="chart_options<%= index %> mutuallyexclusive<%= index %>" id="sum_<%= index %>" >
    <option value=""></option>
    <option value="10">10</option>
    <option value="15">15</option>
    <option value="20">20</option>
    <option value="30">30</option>
    <option value="60">60</option>
    <option value="240">240</option>
    <option value="720">720</option>
    <option value="1440">1440</option>
  </select>
      </td>
    </tr>
    <tr>
      <td><%= t(:chart_round) %>:</td>
      <td><input type="text" class="chart_options<%= index %> shortfield" id="round_<%= index %>" /></td>
    </tr>
    <tr>
      <td><%= t(:chart_min) %>: </td>
      <td><input type="text" class="chart_options<%= index %> shortfield" id="min_<%= index %>" /></td>
    </tr>
    <tr>
      <td><%= t(:chart_max) %>: </td>
      <td><input type="text" class="chart_options<%= index %> shortfield" id="max_<%= index %>" /></td>
    </tr>
    <tr>
      <td><%= t(:chart_yaxis_min) %>: </td>
      <td><input type="text" class="chart_options<%= index %> shortfield" id="yaxismin_<%= index %>" /></td>
    </tr>
    <tr>
      <td><%= t(:chart_yaxis_max) %>: </td>
      <td><input type="text" class="chart_options<%= index %> shortfield" id="yaxismax_<%= index %>" /></td>
    </tr>
    <tr>
      <td><input type="button" id="button<%= index %>" value="<%= t(:chart_update) %>" /></td>
      <td></td>
    </tr>
  </table>

<% if displayconfig %>
  <%= render :partial => 'charts/display',
  :locals => {
  :index => index,
  :width => @width,
  :height => @height,
  :src => src,
  :options => options
  }
  %>
<% end %>

<script type="text/javascript">

  var options = '<%= options.gsub(/'/, "%27") if options %>';

  $(document).on('page:load ready', function() {
  // set initial saved values
    $.each((options.split('&amp;')), setupChartForm(<%= index %> ));
     // draw initial chart with saved options
     var width = <%= (@width) ? @width : 450 %>;
     var height = <%= @height ? @height : 260 %>;
     updateChart(<%= index %>, false, width, height, <%= @channel.id %>);

  });

  // event to capture update button click
  $('#button<%= index %>').click(function() {
   var width = <%= (@width) ? @width : 450 %>;
     var height = <%= @height ? @height : 260 %>;
  updateChart(<%= index %>, true, width, height, <%= @channel.id %>);

  });


  $('.mutuallyexclusive<%= index %>').change(function() {
    selectedValue = $(this).val();
    $('.mutuallyexclusive<%= index %>').each(function () {
        $(this).val("");
    });
    $(this).val(selectedValue);
  });


</script>

thingspeak/app/views/charts/_display.html.erb
  <br class="CL" />

  <iframe id="iframe<%= index %>" width="<%= width %>" height="<%= height %>" style="border: 1px solid #cccccc;" src="" default_src="<%= src %>"></iframe>

  <br><br>

  <%= t(:chart_embed_code) %>:
  <br>
  <textarea id="embed<%= index %>" rows="5" cols="53">&lt;iframe width="<%= width %>" height="<%= height %>" style="border: 1px solid #cccccc;" src="<%= src %>">&lt;/iframe></textarea>

<br><br><br>

thingspeak/app/views/charts/index.html.erb
<div id="maincontent">
  <h2>
    <%= link_to t(:channels), channels_path %> &raquo;
    <%= link_to channel_path(@channel.id) do %> <%= t(:channel) %> <%= @channel.id %><% end %> &raquo;
    <%= t(:charts) %>
  </h2>

  <% if !@channel.active? %>
    <%= render :partial => 'config',
      :locals => {
        :displayconfig => true,
        :title => t(:chart_example),
        :src => "https://api.thingspeak.com/channels/3/charts/1",
        :options => '&timescale=60&round=2',
        :index => 0,
        :width => @width,
        :height => @height
      }
    %>

    <h3><%= t(:chart_owned) %></h3>
  <% end %>

  <% @channel.attribute_names.each do |attr| %>
    <% if attr.index('field') and @channel[attr] and !@channel[attr].empty? %>

      <%= render :partial => 'config',
        :locals => {
                      :displayconfig => true,
          :title => "#{@channel.name} - #{@channel[attr]}",
          :src => "#{@domain}channels/#{@channel_id}/charts/#{attr[-1]}",
          :options => @channel["options#{attr[-1]}"],
          :index => attr[-1],
          :width => @width,
          :height => @height
        }
      %>

    <% end %>
  <% end %>
</div>

<div id="sidebar">
  <ul>
    <li>
      <div class="helplink">(<a href="/docs/charts"><%= t(:help_options) %></a>)</div>
      <h2><%= t(:help_charts) %></h2>
      <%= t(:help_charts_options) %>
      <br><br>
      <%= t(:help_charts_embed) %>
      <br><br>
      &bull; <a href="http://community.thingspeak.com/tutorials/wordpress/how-to-embed-a-thingspeak-chart-on-your-wordpress-blog/">WordPress Tutorial</a>
    </li>
  </ul>
</div>

<script type="text/javascript">

  $(document).on('page:load ready', function() {
    // if chrome/safari error occurs, reload page
    if ($('#title0').val() == '60' && $('#color0').val() == '10') {
      window.location.reload();
    }
  });

</script>

thingspeak/app/views/charts/multiple_series.html.erb
<!DOCTYPE html>
<html style="height: 100%;">
  <head>
    <script type="text/javascript" src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
    <script type="text/javascript" src="//thingspeak.com/highcharts-3.0.8.js"></script>
    <script type="text/javascript" src="//thingspeak.com/exporting.js"></script>

    <script type="text/javascript">
      // variables for the first series
      var series_1_channel_id = 9;
      var series_1_field_number = 1;
      var series_1_read_api_key = '';
      var series_1_results = 10;
      var series_1_color = '#d62020';

      // variables for the second series
      var series_2_channel_id = 9;
      var series_2_field_number = 2;
      var series_2_read_api_key = '';
      var series_2_results = 10;
      var series_2_color = '#00aaff';

      // chart title
      var chart_title = 'Light & Temperature';
      // y axis title
      var y_axis_title = 'Values';

      // user's timezone offset
      var my_offset = new Date().getTimezoneOffset();
      // chart variable
      var my_chart;

      // when the document is ready
      $(document).on('ready', function() {
        // add a blank chart
        addChart();
        // add the first series
        addSeries(series_1_channel_id, series_1_field_number, series_1_read_api_key, series_1_results, series_1_color);
        // add the second series
        addSeries(series_2_channel_id, series_2_field_number, series_2_read_api_key, series_2_results, series_2_color);
      });

      // add the base chart
      function addChart() {
        // variable for the local date in milliseconds
        var localDate;

        // specify the chart options
        var chartOptions = {
          chart: {
            renderTo: 'chart-container',
            defaultSeriesType: 'line',
            backgroundColor: '#ffffff',
            events: { }
          },
          title: { text: chart_title },
          plotOptions: {
            series: {
              marker: { radius: 3 },
              animation: true,
              step: false,
              borderWidth: 0,
              turboThreshold: 0
            }
          },
          tooltip: {
            // reformat the tooltips so that local times are displayed
            formatter: function() {
              var d = new Date(this.x + (my_offset*60000));
              var n = (this.point.name === undefined) ? '' : '<br>' + this.point.name;
              return this.series.name + ':<b>' + this.y + '</b>' + n + '<br>' + d.toDateString() + '<br>' + d.toTimeString().replace(/\(.*\)/, "");
            }
          },
          xAxis: {
            type: 'datetime',
            title: { text: 'Date' }
          },
          yAxis: { title: { text: y_axis_title } },
          exporting: { enabled: false },
          legend: { enabled: false },
          credits: {
            text: 'ThingSpeak.com',
            href: 'https://thingspeak.com/',
            style: { color: '#D62020' }
          }
        };

        // draw the chart
        my_chart = new Highcharts.Chart(chartOptions);
      }

      // add a series to the chart
      function addSeries(channel_id, field_number, api_key, results, color) {
        var field_name = 'field' + field_number;

        // get the data with a webservice call
        $.getJSON('https://api.thingspeak.com/channels/' + channel_id + '/fields/' + field_number + '.json?offset=0&round=2&results=' + results + '&api_key=' + api_key, function(data) {

          // blank array for holding chart data
          var chart_data = [];

          // iterate through each feed
          $.each(data.feeds, function() {
            var point = new Highcharts.Point();
            // set the proper values
            var value = this[field_name];
            point.x = getChartDate(this.created_at);
            point.y = parseFloat(value);
            // add location if possible
            if (this.location) { point.name = this.location; }
            // if a numerical value exists add it
            if (!isNaN(parseInt(value))) { chart_data.push(point); }
          });

          // add the chart data
          my_chart.addSeries({ data: chart_data, name: data.channel[field_name], color: color });
        });
      }

      // converts date format from JSON
      function getChartDate(d) {
        // get the data using javascript's date object (year, month, day, hour, minute, second)
        // months in javascript start at 0, so remember to subtract 1 when specifying the month
        // offset in minutes is converted to milliseconds and subtracted so that chart's x-axis is correct
        return Date.UTC(d.substring(0,4), d.substring(5,7)-1, d.substring(8,10), d.substring(11,13), d.substring(14,16), d.substring(17,19)) - (my_offset * 60000);
      }

  </script>
</head>
<body style='background-color: white; height: 100%; margin: 0; padding: 0;'>
  <div id="chart-container" style="width: 800px; height: 400px; display: block; position:absolute; bottom:0; top:0; left:0; right:0; margin: 5px 15px 15px 0; overflow: hidden;">
    <%= image_tag 'ajax-loader.gif', :style => "position: absolute; margin: auto; top: 0; left: 0; right: 0; bottom: 0;" %>
  </div>
</body>
</html>